version: '3'
services:
  jenkins: 
    image: jenkins/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - C:\jenkins\jenkins_course:/var/jenkins_home
    networks:
      - net
networks:
  net: